package javiertorres.amazonconbackend22settembre.service;
import javiertorres.amazonconbackend22settembre.dto.AuthDtos.*; import javiertorres.amazonconbackend22settembre.entity.*; import javiertorres.amazonconbackend22settembre.exception.ApiExceptions; import javiertorres.amazonconbackend22settembre.repository.*; import javiertorres.amazonconbackend22settembre.security.JwtService; import java.util.UUID; import java.util.stream.Collectors; import org.springframework.security.authentication.BadCredentialsException; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service;
@Service public class AuthService { private final UtenteRepository utenti; private final RoleRepository ruoli; private final PasswordEncoder encoder; private final JwtService jwt; public AuthService(UtenteRepository u,RoleRepository r,PasswordEncoder e,JwtService j){utenti=u;ruoli=r;encoder=e;jwt=j;}
 public AuthResponse register(RegisterRequest x){if(utenti.existsByEmailIgnoreCase(x.email())||utenti.existsByUsernameIgnoreCase(x.username()))throw new ApiExceptions.Duplicate("Username o email già registrati");Role role=ruoli.findByName("USER").orElseGet(()->ruoli.save(new Role("USER")));Utente u=new Utente(x.username(),x.email().toLowerCase(),encoder.encode(x.password()),x.firstName(),x.lastName());u.getRoles().add(role);utenti.save(u);return response(u);}
 public AuthResponse login(LoginRequest x){Utente u=utenti.findByEmailIgnoreCase(x.email()).orElseThrow(()->new BadCredentialsException("Credenziali non valide"));if(!encoder.matches(x.password(),u.getPassword()))throw new BadCredentialsException("Credenziali non valide");return response(u);}
 public UserResponse grantAdmin(UUID id){Utente u=utenti.findById(id).orElseThrow(()->new ApiExceptions.NotFound("Utente non trovato"));u.getRoles().add(ruoli.findByName("ADMIN").orElseGet(()->ruoli.save(new Role("ADMIN"))));return userResponse(utenti.save(u));}
 public UserResponse revokeAdmin(UUID id){Utente u=utenti.findById(id).orElseThrow(()->new ApiExceptions.NotFound("Utente non trovato"));u.getRoles().removeIf(r->r.getName().equals("ADMIN"));return userResponse(utenti.save(u));}
 private AuthResponse response(Utente u){var names=u.getRoles().stream().map(Role::getName).collect(Collectors.toSet());return new AuthResponse(jwt.generate(u.getEmail(),names),userResponse(u));} private UserResponse userResponse(Utente u){return new UserResponse(u.getId(),u.getEmail(),u.getFirstName(),u.getLastName(),u.getRoles().stream().map(Role::getName).collect(Collectors.toSet()));}
}
